# Generated by Django 4.2.5 on 2024-08-12 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_meal_drinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftmeal',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_meals', to='api.meal', verbose_name='وعده'),
        ),
    ]
